project_id = "avzyuhhbmzhxqksnficn"

[functions.meta-oauth-callback]
verify_jwt = false

[functions.get-instagram-accounts]
enabled = true
verify_jwt = true
import_map = "./functions/get-instagram-accounts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-instagram-accounts/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-instagram-accounts/*.html" ]
